version: "3.7"
services:
        slasher:
                image: tianon/true
                restart: "no"
                command: ""
                entrypoint: ""
        prometheus:
                image: tianon/true
                restart: "no"
                command: ""
                entrypoint: ""
        grafana:
                image: tianon/true
                restart: "no"
                command: ""
                entrypoint: ""

