version: "3.7"

x-disabled-service:
        &disabled-service
                image: tianon/true
                restart: "no"
                command: ""
                entrypoint: ""

services:
        geth:
                <<: *disabled-service
        beacon:
                volumes:
                        - ./config/beacon-no-geth.yaml:/config/beacon.yaml:ro
                        - ./beacon:/data
        slasher:
                <<: *disabled-service
        prometheus:
                <<: *disabled-service
        grafana:
                <<: *disabled-service
