version: "3.7"

x-disabled-service:
        &disabled-service
                image: tianon/true
                restart: "no"
                command: ""
                entrypoint: ""

services:
        geth:
                <<: *disabled-service
        beacon:
                image: eth2spectrum/prysm-beacon-chain-arm64:${PRYSM_DOCKER_TAG}
                volumes:
                        - ./config/beacon-no-geth.yaml:/config/beacon.yaml:ro
                        - ./beacon:/data
        validator:
                image: eth2spectrum/prysm-validator-arm64:${PRYSM_DOCKER_TAG}
        slasher:
                image: eth2spectrum/prysm-slasher-arm64:${PRYSM_DOCKER_TAG}