############################################################
##
## Read up on parameters on
## https://docs.prylabs.network/docs/prysm-usage/parameters/
##
############################################################

datadir: /data

#######################
# Connectivity settings 
p2p-host-ip: 116.203.246.230
p2p-host-dns: ""

# changing this also needs to be changed in docker-compose.yaml!
p2p-tcp-port: 13000

##############################
# Connection to geth container
http-web3provider: http://geth:8545
web3provider: ws://geth:8546
