############################################################
##
## Read up on parameters on
## https://docs.prylabs.network/docs/prysm-usage/parameters/
##
############################################################

##############
# Connectivity
beacon-rpc-provider: beacon:4000

#####################################
# Validator accounts & key management
keymanager: keystore
keymanageropts: /data/keystore.json

############
# Monitoring
enable-account-metrics: true

###############
# gRPC security
tls-cert: /config/tls/beacon.crt
